import type { Outage } from "./mockDataTypes";

const ago = (ms: number): string => new Date(Date.now() - ms).toISOString();

export const mockOutages: Outage[] = [
  {
    id: "out-001",
    lat: 18.6298,
    lng: 73.7997,
    area: "Akurdi Naka",
    complaintCategory: "safety",
    complaintType: "live_wire",
    severity: "emergency",
    substationName: "22/22 kV Akurdi (SS-213013)",
    feederName: "Feeder 301 – Akurdi I",
    dpNumber: "DP-517-309-0042",
    poleNumber: "AKD-301-P012",
    status: "reported",
    reportedBy: "9999999999",
    timestamp: ago(15 * 60000),
    confirmations: ["user1", "user2", "user3"],
    adminMessage: null,
    description:
      "Live wire fallen on road near Akurdi Naka, extremely dangerous",
  },
  {
    id: "out-002",
    lat: 18.618,
    lng: 73.8009,
    area: "Pimpri Chowk",
    complaintCategory: "safety",
    complaintType: "sparking",
    severity: "critical",
    substationName: "33/11 kV Pimpri",
    feederName: "Feeder 1 – Pimpri Market",
    dpNumber: "DP-517-309-0118",
    poleNumber: "PMP-F1-P041",
    status: "acknowledged",
    reportedBy: "9876543210",
    timestamp: ago(45 * 60000),
    confirmations: ["user1", "user2"],
    adminMessage: "Team dispatched",
    description: "Heavy sparking visible on pole near Pimpri market",
  },
  {
    id: "out-003",
    lat: 18.6522,
    lng: 73.8394,
    area: "Bhosari MIDC",
    complaintCategory: "infrastructure",
    complaintType: "transformer_fault",
    severity: "moderate",
    substationName: "220 kV Bhosari",
    feederName: "Feeder 1 – Bhosari MIDC Gate",
    dpNumber: "DP-517-309-0203",
    poleNumber: "BHS-F1-P007",
    status: "in_progress",
    reportedBy: "9123456789",
    timestamp: ago(2 * 3600000),
    confirmations: ["user1"],
    adminMessage: "Transformer replacement in progress",
    description: "Transformer tripped, entire sector without power",
  },
  {
    id: "out-004",
    lat: 18.5975,
    lng: 73.7898,
    area: "Chinchwad Station",
    complaintCategory: "supply",
    complaintType: "complete_cut",
    severity: "moderate",
    substationName: "220 kV Chinchwad-1",
    feederName: "Feeder 1 – Chinchwad Station",
    dpNumber: "DP-517-309-0311",
    poleNumber: "CHW-F1-P019",
    status: "reported",
    reportedBy: "9988776655",
    timestamp: ago(30 * 60000),
    confirmations: ["user1", "user2", "user3", "user4"],
    adminMessage: null,
    description: "Complete blackout in residential area near station",
  },
  {
    id: "out-005",
    lat: 18.6489,
    lng: 73.7739,
    area: "Nigdi Pradhikaran",
    complaintCategory: "supply",
    complaintType: "low_voltage",
    severity: "minor",
    substationName: "33/11 kV Nigdi",
    feederName: "Feeder 3 – Pradhikaran",
    dpNumber: "DP-517-309-0089",
    poleNumber: "NGD-F3-P022",
    status: "reported",
    reportedBy: "9765432100",
    timestamp: ago(90 * 60000),
    confirmations: ["user1"],
    adminMessage: null,
    description: "Very low voltage, appliances not working properly",
  },
  {
    id: "out-006",
    lat: 18.589,
    lng: 73.7612,
    area: "Thergaon",
    complaintCategory: "scheduled",
    complaintType: "maintenance",
    severity: "minor",
    substationName: "33/11 kV Kalewadi",
    feederName: "Feeder 1 – Kalewadi Phata",
    dpNumber: "DP-517-309-0156",
    poleNumber: "KLD-F1-P033",
    status: "acknowledged",
    reportedBy: "MSEDCL",
    timestamp: ago(4 * 3600000),
    confirmations: [],
    adminMessage: "Planned maintenance 9AM–2PM",
    description: "Scheduled line maintenance work",
  },
  {
    id: "out-007",
    lat: 18.5641,
    lng: 73.7688,
    area: "Wakad Bridge",
    complaintCategory: "safety",
    complaintType: "tree_on_ht",
    severity: "emergency",
    substationName: "33/11 kV Kalewadi",
    feederName: "Feeder 2 – Rahatani",
    dpNumber: "DP-517-309-0274",
    poleNumber: "KLD-F2-P018",
    status: "reported",
    reportedBy: "9654321087",
    timestamp: ago(10 * 60000),
    confirmations: ["user1", "user2"],
    adminMessage: null,
    description:
      "Large tree branch fallen on HT wire, line sagging dangerously",
  },
  {
    id: "out-008",
    lat: 18.5912,
    lng: 73.7191,
    area: "Hinjawadi Phase 1",
    complaintCategory: "supply",
    complaintType: "voltage_fluctuation",
    severity: "moderate",
    substationName: "33 kV Hinjawadi IT Park",
    feederName: "Feeder 1 – Phase I",
    dpNumber: "DP-517-309-0390",
    poleNumber: "HNJ-F1-P055",
    status: "in_progress",
    reportedBy: "9543210876",
    timestamp: ago(3 * 3600000),
    confirmations: ["user1", "user2", "user3"],
    adminMessage: "Team checking feeder",
    description: "Severe voltage fluctuation causing UPS alarms in IT offices",
  },
];

export const mockHistory: Outage[] = [
  {
    id: "hist-001",
    lat: 18.6298,
    lng: 73.7997,
    area: "Akurdi",
    complaintCategory: "infrastructure",
    complaintType: "fuse_blown",
    severity: "minor",
    substationName: "22/22 kV Akurdi (SS-213013)",
    feederName: "Feeder 302 – Akurdi II",
    dpNumber: "DP-517-309-0042",
    poleNumber: "AKD-302-P034",
    status: "resolved",
    reportedBy: "9999999999",
    timestamp: ago(24 * 3600000),
    confirmations: ["user1", "user2"],
    adminMessage: "Fuse replaced",
    description: "Fuse blown on main line",
    resolvedAt: ago(20 * 3600000),
  },
  {
    id: "hist-002",
    lat: 18.618,
    lng: 73.8009,
    area: "Pimpri",
    complaintCategory: "safety",
    complaintType: "meter_sparking",
    severity: "critical",
    substationName: "33/11 kV Pimpri",
    feederName: "Feeder 2 – Pimpri Chowk",
    dpNumber: "DP-517-309-0118",
    poleNumber: "PMP-F2-P009",
    status: "resolved",
    reportedBy: "9876543210",
    timestamp: ago(48 * 3600000),
    confirmations: ["user1"],
    adminMessage: "Meter box replaced",
    description: "Meter box sparking, consumer disconnected temporarily",
    resolvedAt: ago(44 * 3600000),
  },
  {
    id: "hist-003",
    lat: 18.6522,
    lng: 73.8394,
    area: "Bhosari",
    complaintCategory: "supply",
    complaintType: "single_phase",
    severity: "moderate",
    substationName: "220 kV Bhosari",
    feederName: "Feeder 2 – Bhosari Village",
    dpNumber: "DP-517-309-0203",
    poleNumber: "BHS-F2-P021",
    status: "resolved",
    reportedBy: "9123456789",
    timestamp: ago(72 * 3600000),
    confirmations: ["user1", "user2", "user3"],
    adminMessage: "Phase restored",
    description: "One phase dead in colony",
    resolvedAt: ago(68 * 3600000),
  },
  {
    id: "hist-004",
    lat: 18.5641,
    lng: 73.7688,
    area: "Wakad",
    complaintCategory: "infrastructure",
    complaintType: "pole_damaged",
    severity: "critical",
    substationName: "33/11 kV Kalewadi",
    feederName: "Feeder 2 – Rahatani",
    dpNumber: "DP-517-309-0274",
    poleNumber: "KLD-F2-P011",
    status: "resolved",
    reportedBy: "9654321087",
    timestamp: ago(96 * 3600000),
    confirmations: ["user1", "user2"],
    adminMessage: "Pole replaced",
    description: "Pole damaged by truck collision",
    resolvedAt: ago(90 * 3600000),
  },
  {
    id: "hist-005",
    lat: 18.5912,
    lng: 73.7191,
    area: "Hinjawadi",
    complaintCategory: "scheduled",
    complaintType: "load_shedding",
    severity: "minor",
    substationName: "33 kV Hinjawadi IT Park",
    feederName: "Feeder 2 – Phase II",
    dpNumber: "DP-517-309-0390",
    poleNumber: "HNJ-F2-P031",
    status: "resolved",
    reportedBy: "MSEDCL",
    timestamp: ago(120 * 3600000),
    confirmations: [],
    adminMessage: "Load shedding completed as scheduled",
    description: "Scheduled load shedding 6AM–8AM",
    resolvedAt: ago(118 * 3600000),
  },
];
