import type { Outage } from "./mockDataTypes";

export const mockHistory: Outage[] = [
  {
    id: "hist-001",
    lat: 18.6271,
    lng: 73.8003,
    area: "Akurdi Colony",
    complaintCategory: "infrastructure",
    complaintType: "fuse_blown",
    severity: "minor",
    substationName: "22/22 kV Akurdi (SS-213013)",
    feederName: "Feeder 302 – Akurdi II",
    dpNumber: "DP-517-309-0042",
    poleNumber: "AKD-302-P034",
    status: "resolved",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    confirmations: ["u1", "u2"],
    adminMessage: "Fuse replaced, supply restored",
    description: "Main line fuse blown after overload, 3 buildings affected",
    resolvedAt: new Date(Date.now() - 20 * 3600000).toISOString(),
  },
  {
    id: "hist-002",
    lat: 18.6155,
    lng: 73.8021,
    area: "Pimpri Camp",
    complaintCategory: "infrastructure",
    complaintType: "short_circuit",
    severity: "critical",
    substationName: "33/11 kV Pimpri",
    feederName: "Feeder 2 – Pimpri Chowk",
    dpNumber: "DP-517-309-0118",
    poleNumber: "PMP-F2-P009",
    status: "resolved",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
    confirmations: ["u1"],
    adminMessage: "Short circuit cleared, insulation replaced",
    description: "Short circuit between phases caused by water ingress after heavy rain",
    resolvedAt: new Date(Date.now() - 44 * 3600000).toISOString(),
  },
  {
    id: "hist-003",
    lat: 18.65,
    lng: 73.841,
    area: "Bhosari Village",
    complaintCategory: "supply",
    complaintType: "single_phase",
    severity: "moderate",
    substationName: "220 kV Bhosari",
    feederName: "Feeder 2 – Bhosari Village",
    dpNumber: "DP-517-309-0203",
    poleNumber: "BHS-F2-P021",
    status: "resolved",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 72 * 3600000).toISOString(),
    confirmations: ["u1", "u2", "u3"],
    adminMessage: "Single phase fault cleared, all three phases restored",
    description: "One of three phases dead, partial supply, motors not starting",
    resolvedAt: new Date(Date.now() - 68 * 3600000).toISOString(),
  },
  {
    id: "hist-004",
    lat: 18.562,
    lng: 73.77,
    area: "Wakad Road",
    complaintCategory: "infrastructure",
    complaintType: "pole_damaged",
    severity: "critical",
    substationName: "33/11 kV Kalewadi",
    feederName: "Feeder 2 – Rahatani",
    dpNumber: "DP-517-309-0274",
    poleNumber: "KLD-F2-P011",
    status: "resolved",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 96 * 3600000).toISOString(),
    confirmations: ["u1", "u2"],
    adminMessage: "Damaged pole replaced, line restored",
    description: "Concrete pole cracked and tilted after heavy vehicle collision",
    resolvedAt: new Date(Date.now() - 90 * 3600000).toISOString(),
  },
  {
    id: "hist-005",
    lat: 18.593,
    lng: 73.721,
    area: "Hinjawadi Phase 2",
    complaintCategory: "scheduled",
    complaintType: "load_shedding",
    severity: "minor",
    substationName: "33 kV Hinjawadi IT Park",
    feederName: "Feeder 2 – Phase II",
    dpNumber: "DP-517-309-0390",
    poleNumber: "HNJ-F2-P031",
    status: "resolved",
    reportedBy: "MSEDCL",
    timestamp: new Date(Date.now() - 120 * 3600000).toISOString(),
    confirmations: [],
    adminMessage: "Load shedding completed as per schedule",
    description: "Scheduled load shedding 6AM–8AM as per MSEDCL roster",
    resolvedAt: new Date(Date.now() - 118 * 3600000).toISOString(),
  },
];
