import type { Outage } from "./mockDataTypes";

export const mockOutages: Outage[] = [
  {
    id: "out-001",
    lat: 18.6298,
    lng: 73.7997,
    area: "Akurdi Naka, PCMC",
    complaintCategory: "safety",
    complaintType: "live_wire",
    severity: "emergency",
    substationName: "22/22 kV Akurdi (SS-213013)",
    feederName: "Feeder 301 – Akurdi I",
    dpNumber: "DP-517-309-0042",
    poleNumber: "AKD-301-P012",
    status: "reported",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    confirmations: ["u1", "u2", "u3"],
    adminMessage: null,
    description: "Live wire snapped and lying on road near Akurdi bus stop, vehicles passing over it",
  },
  {
    id: "out-002",
    lat: 18.618,
    lng: 73.8009,
    area: "Pimpri Chowk",
    complaintCategory: "safety",
    complaintType: "sparking",
    severity: "critical",
    substationName: "33/11 kV Pimpri",
    feederName: "Feeder 1 – Pimpri Market",
    dpNumber: "DP-517-309-0118",
    poleNumber: "PMP-F1-P041",
    status: "acknowledged",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
    confirmations: ["u1", "u2"],
    adminMessage: "Team on the way",
    description: "Continuous sparking from pole junction box near Pimpri market, smell of burning",
  },
  {
    id: "out-003",
    lat: 18.6522,
    lng: 73.8394,
    area: "Bhosari MIDC Gate",
    complaintCategory: "infrastructure",
    complaintType: "transformer_fault",
    severity: "moderate",
    substationName: "220 kV Bhosari",
    feederName: "Feeder 1 – Bhosari MIDC Gate",
    dpNumber: "DP-517-309-0203",
    poleNumber: "BHS-F1-P007",
    status: "in_progress",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    confirmations: ["u1"],
    adminMessage: "Transformer replacement underway, ETA 3 hours",
    description: "Distribution transformer tripped, entire MIDC block without supply",
  },
  {
    id: "out-004",
    lat: 18.5975,
    lng: 73.7898,
    area: "Chinchwad Station Road",
    complaintCategory: "supply",
    complaintType: "complete_cut",
    severity: "moderate",
    substationName: "220 kV Chinchwad-1",
    feederName: "Feeder 1 – Chinchwad Station",
    dpNumber: "DP-517-309-0311",
    poleNumber: "CHW-F1-P019",
    status: "reported",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    confirmations: ["u1", "u2", "u3", "u4"],
    adminMessage: null,
    description: "Total blackout in residential colony, no supply since last 35 minutes",
  },
  {
    id: "out-005",
    lat: 18.6489,
    lng: 73.7739,
    area: "Nigdi Sector 27",
    complaintCategory: "supply",
    complaintType: "low_voltage",
    severity: "minor",
    substationName: "33/11 kV Nigdi",
    feederName: "Feeder 3 – Pradhikaran",
    dpNumber: "DP-517-309-0089",
    poleNumber: "NGD-F3-P022",
    status: "reported",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    confirmations: ["u1"],
    adminMessage: null,
    description: "Voltage too low since morning, fans running slow, fridge not cooling",
  },
  {
    id: "out-006",
    lat: 18.5641,
    lng: 73.7688,
    area: "Wakad Bridge",
    complaintCategory: "safety",
    complaintType: "tree_on_ht",
    severity: "emergency",
    substationName: "33/11 kV Kalewadi",
    feederName: "Feeder 2 – Rahatani",
    dpNumber: "DP-517-309-0274",
    poleNumber: "KLD-F2-P018",
    status: "reported",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    confirmations: ["u1", "u2"],
    adminMessage: null,
    description: "Large tree fell on 11kV HT line after rain, wire sagging dangerously low",
  },
  {
    id: "out-007",
    lat: 18.5912,
    lng: 73.7191,
    area: "Hinjawadi Phase 1",
    complaintCategory: "supply",
    complaintType: "voltage_fluctuation",
    severity: "moderate",
    substationName: "33 kV Hinjawadi IT Park",
    feederName: "Feeder 1 – Phase I",
    dpNumber: "DP-517-309-0390",
    poleNumber: "HNJ-F1-P055",
    status: "in_progress",
    reportedBy: "u1",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    confirmations: ["u1", "u2", "u3"],
    adminMessage: "Feeder load balancing in progress",
    description: "Severe fluctuation tripping UPS systems in IT offices, happening every 10 mins",
  },
  {
    id: "out-008",
    lat: 18.589,
    lng: 73.7612,
    area: "Thergaon Phata",
    complaintCategory: "scheduled",
    complaintType: "maintenance",
    severity: "minor",
    substationName: "33/11 kV Kalewadi",
    feederName: "Feeder 1 – Kalewadi Phata",
    dpNumber: "DP-517-309-0156",
    poleNumber: "KLD-F1-P033",
    status: "acknowledged",
    reportedBy: "MSEDCL",
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    confirmations: [],
    adminMessage: "Planned line maintenance 9AM–2PM, supply will be restored by 2PM",
    description: "MSEDCL scheduled maintenance work on 11kV feeder line",
  },
];
